language: android
jdk: oraclejdk8
dist: trusty

android:
  components:
    - build-tool-30.0.2
    - android-30
    - extra

before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-26"