language: android
jdk: oraclejdk8
dist: trusty

android:
  components:
    - build-tool-30.0.2
    - android-30
    - extra
    - sys-img-armeabi-v7a-android-30

before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-30"

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-30 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - android list target
  - ./gradlew connectedAndroidTest