language: android
jdk: oraclejdk8
dist: trusty

env:
  matrix:
    - ANDROID_TARGET=android-30  ANDROID_ABI=google_apis/armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    - build-tool-30.0.2
    - android-30
    - extra
    - sys-img-armeabi-v7a-$ANDROID_TARGET

before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-30"

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t "Google Inc.:Google APIs:"$ANDROID_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script: ./gradlew connectedAndroidTest